# INF-0616 - Aula 1: Exercícios python e numpy

Professora: Esther Colombini -- esther@ic.unicamp.br

Monitores: Alana Santana -- alana.correia@ic.unicamp.br
           Hudson Bruno -- hudson.bruno@ic.unicamp.br

Este *notebook* faz parte da disciplina INF-0616 no curso de extensão MDC.  
Demais artefatos podem ser encontrados no moodle da disciplina: 
[moodle.lab.ic.unicamp.br/456](https://moodle.lab.ic.unicamp.br/moodle/course/view.php?id=456)

Instituto de Computação - Unicamp 2021

Importamos algumas bibliotecas que podem ser úteis abaixo. Você não precisa fazer nada nesta célula.

In [ ]:
import numpy as np

**Exercício 1:** construa uma lista contendo 100 números, em ordem crescente.

In [ ]:
l = []                       # 1
for i in range(100):
    l += [i]

l = [i for i in range(100)]  # 2

l = np.arange(100)           # 3

print(l)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


**Exercício 2:** some todos os valores contidos na lista anterior.

In [ ]:
sum(l)

4950

**Exercício 3:** re-formate a lista criada anteriormente em uma matriz de tamanho $10\times 10$.

In [ ]:
m = []                      # 1
for i in range(0, 100, 10):
    m += [l[i:i+10]]
m = np.asarray(m)

m = l.reshape(10, 10)       # 2

print(m)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


**Exercício 4:** múltiplique a matriz anterior por sua transposta.

In [ ]:
m.dot(m.T).tolist()

[[285, 735, 1185, 1635, 2085, 2535, 2985, 3435, 3885, 4335],
 [735, 2185, 3635, 5085, 6535, 7985, 9435, 10885, 12335, 13785],
 [1185, 3635, 6085, 8535, 10985, 13435, 15885, 18335, 20785, 23235],
 [1635, 5085, 8535, 11985, 15435, 18885, 22335, 25785, 29235, 32685],
 [2085, 6535, 10985, 15435, 19885, 24335, 28785, 33235, 37685, 42135],
 [2535, 7985, 13435, 18885, 24335, 29785, 35235, 40685, 46135, 51585],
 [2985, 9435, 15885, 22335, 28785, 35235, 41685, 48135, 54585, 61035],
 [3435, 10885, 18335, 25785, 33235, 40685, 48135, 55585, 63035, 70485],
 [3885, 12335, 20785, 29235, 37685, 46135, 54585, 63035, 71485, 79935],
 [4335, 13785, 23235, 32685, 42135, 51585, 61035, 70485, 79935, 89385]]

**Exercício 5:** construa uma matriz de tamanho $3\times 3$, contendo $1s$ sobre a diagonal principal e $0$ nas demais posições (i.e., a matriz `eye`).

In [ ]:
e = np.zeros((3, 3))            # 1
e[0, 0] = e[1, 1] = e[2, 2] = 1

e = np.eye(3, 3)                # 2

print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Exercício 6:** múltiplique a matriz anterior por sua transposta.

In [ ]:
e.dot(e.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Exercício 7:** randomize a posição dos elementos da lista construída no item 1.

In [ ]:
np.random.shuffle(l)

print(l)

[10 38 97 24 48 78 61 71 85  7  9 72 66 96 41 30 11 82 69 89 80 92 62 57
  5 13 40 26 44 51 42 67 37 53 50 68 63 45 74 60  3 23 91 94 47 18 70 86
 20  1 52 88 31 25 22 64  0 99 54 28 87 58 17  2 56 46 59 55 15 21 27 79
 32 73 65 19 83 76 12  4 90 77 95 16 33 98 49 35 43 34 75  6 84  8 93 36
 39 81 29 14]


**Exercício 7:** identifique os índices dos três maiores elementos da lista no item 7.

In [ ]:
indices = np.argsort(l)[-3:]

print('indices:', indices,
      'valores:', l[indices])

indices: [ 2 85 57] valores: [97 98 99]


**Exercício 8:** construa uma matriz $P$ de tamanho $78\times 10$, contendo valores aleatórios contídos no intervalo $[0, 1)$.

In [ ]:
P = np.random.rand(78, 10)

P[:10].round(1)

array([[0.1, 0.4, 0.5, 0.4, 0.4, 0.2, 0.2, 0.1, 0.3, 0.1],
       [0.9, 0.6, 0.6, 0.6, 0.1, 0.4, 0.1, 0.7, 0.6, 0. ],
       [1. , 0.1, 0.1, 0.5, 0.9, 0.8, 0.9, 0.5, 0.7, 0.7],
       [0.7, 1. , 0.8, 0.9, 1. , 0.8, 0.8, 0.8, 0. , 0.3],
       [1. , 0.5, 0.6, 0. , 1. , 0.9, 1. , 0.3, 0.3, 0.5],
       [0.3, 0.5, 0.7, 0.9, 0.7, 0.6, 0.7, 0.7, 0.5, 0.9],
       [0.9, 0.5, 0.2, 0.6, 0.2, 0.8, 0.1, 0.6, 0.7, 0. ],
       [0.2, 0.1, 0.6, 0.5, 0.3, 0.7, 0.2, 0.1, 0.7, 0.1],
       [0.5, 0.3, 0.2, 0.5, 0.7, 0.9, 0.3, 0.7, 0.2, 0.6],
       [0.2, 0. , 0.5, 0.4, 0.3, 0.8, 0.9, 0.5, 0.7, 0.9]])

**Exercício 9:** construa um vetor $V = [v_0, v_1, ..., v_n]$ contendo exatamente $78$ posições, tal que $v_i$ representa o índice referente ao maior valor contido na linha $i$ da matriz $P$.

In [ ]:
v = []                        # 1
for i in range(71):
    v.append(np.argmax(P[i]))

v = [np.argmax(r) for r in P] # 2

v = np.argmax(P, axis=1)      # 3

print(v)

[2 0 0 1 4 3 0 5 5 9 1 5 3 0 9 4 1 3 9 7 7 5 6 1 4 6 6 2 0 7 1 9 9 5 7 9 4
 6 0 7 8 4 0 2 8 5 7 7 7 5 4 2 0 1 7 4 4 4 6 4 9 4 4 1 4 3 8 9 5 5 3 6 4 1
 7 1 4 1]


**Exercício 10:** calcule a média e o desvio padrão de cada coluna da matriz $P$.

In [ ]:
print('média:', P.mean(axis=0).round(2))
print('desvio:', P.std(axis=0).round(2))

média: [0.53 0.49 0.52 0.48 0.5  0.56 0.43 0.5  0.52 0.51]
desvio: [0.3  0.29 0.26 0.28 0.32 0.3  0.29 0.31 0.27 0.31]
